project(Editor LANGUAGES C CXX VERSION 1.0.0)

file(GLOB_RECURSE
	EDITOR_SOURCES
		${PROJECT_SOURCE_DIR}/src/*.h
		${PROJECT_SOURCE_DIR}/src/*.c
		${PROJECT_SOURCE_DIR}/src/*.hpp
		${PROJECT_SOURCE_DIR}/src/*.cpp)

source_group(TREE ${CMAKE_CURRENT_SOURCE_DIR} FILES ${EDITOR_SOURCES})

add_executable(Editor ${EDITOR_SOURCES})
target_include_directories(Editor PRIVATE ${PROJECT_SOURCE_DIR}/src)
target_link_libraries(Editor PRIVATE Engine)


if (CMAKE_IMPORT_LIBRARY_SUFFIX AND WIN32)
	set(AGILITY_OUT $<TARGET_FILE_DIR:${PROJECT_NAME}>/D3D12)
	set(AGILITY_PDB_LOCATION ${DirectX-AgilitySDK_SOURCE_DIR}/build/native/bin/x64)

	add_custom_command(
			TARGET ${PROJECT_NAME} POST_BUILD
			COMMAND ${CMAKE_COMMAND} -E copy $<TARGET_RUNTIME_DLLS:${PROJECT_NAME}> $<TARGET_FILE_DIR:${PROJECT_NAME}>
			COMMAND ${CMAKE_COMMAND} -E make_directory ${AGILITY_OUT}
			COMMAND ${CMAKE_COMMAND} -E rename $<TARGET_FILE_DIR:${PROJECT_NAME}>/D3D12Core.dll ${AGILITY_OUT}/D3D12Core.dll
			COMMAND ${CMAKE_COMMAND} -E rename $<TARGET_FILE_DIR:${PROJECT_NAME}>/d3d12SDKLayers.dll ${AGILITY_OUT}/d3d12SDKLayers.dll
			COMMAND_EXPAND_LISTS)

	if(CMAKE_BUILD_TYPE STREQUAL "Debug")
		add_custom_command(
				TARGET ${PROJECT_NAME} POST_BUILD
				COMMAND ${CMAKE_COMMAND} -E copy ${AGILITY_PDB_LOCATION}/D3D12Core.pdb ${AGILITY_OUT}/D3D12Core.pdb
				COMMAND ${CMAKE_COMMAND} -E copy ${AGILITY_PDB_LOCATION}/d3d12SDKLayers.pdb ${AGILITY_OUT}/d3d12SDKLayers.pdb
				COMMAND_EXPAND_LISTS)
	endif()
endif ()
